### ISSUE TITLE
Define is behaving correctly

### ISSUE THREAD

**Issue by IanVS** [jcollicoat/vite-storybook#1]
Thanks for this repo.  The behavior you're seeing with the `define` option for vite is correct.  See https://vitejs.dev/config/shared-options.html#define for details, but it says:

>Define global constant replacements. Entries will be defined as globals during dev and statically replaced during build.

This means in the production build, `import.meta.env.STORYBOOK_DEFINE` should be turned into the string literal `"vitestorybookdefine"`.  

The same could be happening for `STORYBOOK="true"`, though I'm not positive about that.  Maybe you could check?  It's possible there's a bug there.

**Comment by jcollicoat** [comment]
Hey @IanVS, thanks for your help! I'm still not sure the behaviour is completely as expected, as the `define` object doesn't seem to work in production when set inside our Storybook `main.ts` file (it works as expected set from `vite.config.ts`):

Dev:
<img width="448" alt="development" src="https://user-images.githubusercontent.com/28215572/202938353-c61968bf-579e-4d8d-88a6-232048cfc348.png">

Prod:
<img width="440" alt="production" src="https://user-images.githubusercontent.com/28215572/202938362-2ec25f58-2f90-4268-8e38-c86b4eeb4177.png">

Is this how you'd expect this to work between dev/prod? It looks like any variables set in the Storybook `main.ts` are being stripped in prod, regardless of any `VITE_` or `STORYBOOK_` prefixes.

(these console logs are from `Button.tsx`)

**Comment by IanVS** [comment]
Hmmmm, no that doesn't seem right, does it?  Thanks for the investigation and reproduction, I'll try taking a look.

**Comment by jcollicoat** [comment]
Awesome, thank you!

**Comment by jcollicoat** [comment]
@IanVS I've just noticed something else that might be helpful - if I specify the same variable (e.g. `import.meta.env.EXAMPLE`) in both `vite.config.ts` and `main.ts`, it will pull the value inside `main.ts` into production.

**Comment by IanVS** [comment]
I found the cause and pushed up a PR with a fix (https://github.com/storybookjs/storybook/pull/19905).

Thanks again for your thorough reproduction.

**Comment by jcollicoat** [comment]
Amazing, thanks for helping out so quickly! Cheers
